language: generic
sudo: false

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=26.1

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar xf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs

  - openssl aes-256-cbc -K $encrypted_ef6a49253a2d_key -iv $encrypted_ef6a49253a2d_iv -in .travis_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name conao3
  - git config --global user.email conao3@gmail.com

  - git remote -v
  - git remote set-url origin git@github.com:conao3/liskk-dict.git

jobs:
  include:
    - if: branch = master
      stage: "Create dictionary"
      script:
        - make checkout
        - rm -rf utf-8
        - make convert
        - make commit && make merge && make push
